version: '3.5'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/symfony/:cached"
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    restart: always
    depends_on:
      - php
  php:
    build:
      context: ./docker/php/
    restart: always
    env_file:
      - .env
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/symfony/:cached"

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=projects_tasks
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
volumes:
  db-data: { }


