name: Symfony
on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.0.2'
      - uses: actions/checkout@v2
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-plugins --no-scripts --no-progress
      - name: Execute Security check
        run: |
          curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.3/local-php-security-checker_2.0.3_linux_amd64 -o local-php-security-checker
          chmod +x local-php-security-checker
          ./local-php-security-checker
      - name: Execute Unit Tests
        run: vendor/bin/phpunit tests